steps:
- name: python
  entrypoint: pip
  dir: 'app'
  args: ['install', '-r', 'requirments.txt', '--user']

- name: 'gcr.io/cloud-builders/docker'
  dir: 'app'
  args: ['build', '-t', 
         'us-central1-docker.pkg.dev/${PROJECT_ID}/flask-demo-registry/flaskdemo:${SHORT_SHA}', '.']

- name: 'gcr.io/cloud-builders/docker'
  dir: 'app'
  args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/flask-demo-registry/flaskdemo:${SHORT_SHA}']

- name: google/cloud-sdk
  args: ['gcloud', 'run', 'deploy', 'flask-demo-run',
         '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/flask-demo-registry/flaskdemo:${SHORT_SHA}',
         '--region',
         'us-central1',
         '--platform',
         'managed',
         '--allow-unauthenticated',
         '--port',
         '8000']



